### ISSUE TITLE
Feature request support RSS to follow new posts

### ISSUE THREAD

**Issue by JiaxiangBU** [RobertMyles/site#42]
Thanks for your excellent work. I read one of your posts,  https://www.robertmylesmcdonnell.com/content/posts/docker/, an introduction of Docker. It is helpful and clear.
Is there any way to follow your blog? Because I don't find a RSS url ? I just want to receive your updates.

**Comment by RobertMyles** [comment]
Hi @JiaxiangBU , thanks for the suggestion, I'll have a look at implementing it when I get a chance. Happy you liked the Docker post :-)

I'll leave this open until I have it done.

**Comment by RobertMyles** [comment]
Done: https://www.robertmylesmcdonnell.com/rss.xml
Thanks for the suggestion!

**Comment by JiaxiangBU** [comment]
Thanks, I subscribe to it. tidyRSS seems cool, I will try it. @RobertMyles
